version: "3.9"
services:
  telegram_bot:
    build:
      context: telegram_bot_images
      dockerfile: Dockerfile
    environment:
      - PYTHON_HOST=image_processing:${PYTHON_PORT}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - NODE_ENV=development
      - MYSQL_PASS=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_HOST=db
    depends_on:
      - db
  image_processing:
    build:
      context: image_processing_server
      dockerfile: Dockerfile
    environment:
      - PORT=${PYTHON_PORT}
    ports:
      - "${PYTHON_PORT}:${PYTHON_PORT}"
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=telegram_bot
    ports:
      - "${MYSQL_PORT}:3306"